model: bert-base-uncased

preprocess:
  max_sent_len: 512

data:
  data_path: F:\boolq\data
  train_data: train.jsonl
  dev_data: dev.jsonl
  test_data: test.jsonl

train:
  output_dir: ./result
  output_filename_prefix: bert-base-uncased
  logging_step: 200
  batch_size: 12
  epochs: 10
  lr: 0.00003
  weight_decay: 0.01
  b: 0.3

dev:
  batch_size: 8

eval:
  model_path: ./result/bert-base-uncased_epoch=10
  result_dir: ./result
  result_filename: result.txt