model: bert-base-uncased

preprocess:
  max_sent_len: 512

data:
  data_path: /mnt/boolq
  train_data: train.jsonl
  dev_data: dev.jsonl
  test_data: test.jsonl

eda:
  sr_rate: 0.1
  ri_rate: 0.1
  rs_rate: 0.1
  rd_rate: 0.1
  num_aug: 4

train:
  output_dir: ./result
  output_filename_prefix: bert-base-uncased
  logging_step: 200
  batch_size: 8
  epochs: 40
  lr: 0.00003
  weight_decay: 0.01
  b: 0.3

dev:
  batch_size: 8

eval:
  model_path: ./result/bert-base-uncased_epoch=10
  result_dir: ./result
  result_filename: result.txt