model: albert-base-v2

preprocess:
  max_sent_len: 256

data:
  data_path: /home/mingshuo/Dataset/BoolQ
  train_data: train_small.jsonl
  dev_data: dev_small.jsonl
  test_data: test.jsonl

train:
  output_dir: ./result
  output_filename_prefix: albert-base-v2
  logging_step: 100
  batch_size: 2
  epochs: 6
  lr: 0.00003
  weight_decay: 0.001

dev:
  batch_size: 2
